workflows:
  react-native-expo:
    name: React Native Expo Build
    environment:
      node: 16
      npm: 7
    scripts:
      - name: Install Expo CLI
        script: npm install -g expo-cli
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: expo build:android -t apk
    artifacts:
      - build/**/*.apk
      - dist/**/*.apk
      
