workflows:
  expo-build:
    name: Expo Build
    environment:
      node: 16
      npm: 7
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build APK
        script: npx expo build:android -t apk
    artifacts:
      - dist/**/*.apk
      - build/**/*.apk
